export const MOGIVI_CONTENT_TYPE = {
  breadcrumbsProjectPageBlock: "breadcrumbsProjectPageBlock",
  customHeaderContentProjectPageBlock: "customHeaderContentProjectPageBlock",
  projectModuleBlock: "projectModule",
  documentsFiltersBlock: "documentsFiltersBlock",
  vrTourPlaceholder: "vrTourPlaceholder",
  imageCardsBlock: "imageCardsBlock",
  articleFilters: "articleFilters",
  homeLandingPage: "homeLandingPage",
  investorTags: "investorTags",
  instaTourPlaceholder: "instaTourPlaceholder",
  thetaTourPlaceholder: "thetaTourPlaceholder",
  eTSortTagsItem: "eTSortTagsItem",
  eTLocationSuggestionAPIItem: "eTLocationSuggestionAPIItem",
  projectsAPI: "projectsAPI",
  bannerSurveyPriceText: "bannerSurveyPriceText",
  mgvNewsContent: "MgvNewsContent",
  projectModule: "projectModule",
};
